### ISSUE TITLE
No Audio/Assistant Voice for caller

### ISSUE THREAD

**Issue by pinsharp** [thehappydinoa/google-call-screening#3]
Call Screen option seems to working, transcription also working fine..but there is no voice(Assistant Voice) for the person who attends the call (Caller). Help me to Fix

**Comment by thehappydinoa** [comment]
This is an issue with Dialer, waiting for update from Google.

**Comment by pinsharp** [comment]
is it working for you???
if Yes can you link exact APK...so that i can use meantime till update
my Dialer V27.0.2 Beta

**Comment by thehappydinoa** [comment]
It works for me. I use 27.0.225573798-publicbeta

**Comment by pinsharp** [comment]
ehmmm 👍 
why the heck not working for me  👎 :( ehhhhr

**Comment by thehappydinoa** [comment]
I am not 100% sure what device?

**Comment by pinsharp** [comment]
Asus Zenfone Max pro M1
Rom: Pixel Experience 9.0

**Comment by thehappydinoa** [comment]
Are you on the December update?

**Comment by pinsharp** [comment]
yes Android Security Patch Level December 5
+I can hear caller in in-ear speaker :(

**Comment by thehappydinoa** [comment]
Ok, I think we might have to wait for Google to update their dialer.

**Comment by pinsharp** [comment]
ehhmm Lets See btw Thank you :) 👍

**Comment by swxtr** [comment]
Magisk says "it is not a magisk zip" :(
